### ISSUE TITLE
【3.3 线性回归的简洁实现】内容排版问题

### ISSUE THREAD

**Issue by youngxhui** [TrickyGo/Dive-into-DL-TensorFlow2.0#16]
# 多余代码

- 第一行代码多余，可以删去；
- for 循环中的 `x` 原书为 大写 `X`；
- 原书代码结尾有 `break`，这样只会输出一个，可以减少该代码输出后所在内容篇幅。

```python
# dataset=tf.data.Dataset.from_tensor_slices((features,labels))
train_db = tf.data.Dataset.from_tensor_slices((features, labels)).batch(10)
for(x,y) in train_db:
    print(x,y)
```

# 为划分标题

该章节目前没有划分小标题。

# 章节优化器和损失函数在同一章节划分

可以和原书一致，将损失函数和优化器分别定义使用。

# 学习率数值

下面代码原书的学习率采取为 0.03 。
```python
model.compile(optimizer=tf.keras.optimizers.SGD(0.01),
              loss='mse')
```
# 大部分段落没有句号

# 最后多余一个代码块
文章结尾多余一个代码块

![image](https://user-images.githubusercontent.com/16971804/70146150-9bc1b180-16dc-11ea-9d77-c75a5dcb72d7.png)

**Comment by SwordFaith** [comment]
pending
