### ISSUE TITLE
【3.5 图像分类数据集】内容表述错误

### ISSUE THREAD

**Issue by youngxhui** [TrickyGo/Dive-into-DL-TensorFlow2.0#17]
![image](https://user-images.githubusercontent.com/16971804/70151555-b9941400-16e6-11ea-9316-ee0b084f19d1.png)

这里是二维的 array 数组存储。

图像也不是灰度图像。
![image](https://user-images.githubusercontent.com/16971804/70152033-6ec6cc00-16e7-11ea-9097-5da556df1e66.png)

**Comment by youngxhui** [comment]
另外缺失 3.5_output1.png 图像

![3 5_output1](https://user-images.githubusercontent.com/16971804/70152504-4ee3d800-16e8-11ea-970d-c4662125617f.png)

**Comment by archersama** [comment]
了解，这周解决

**Comment by SwordFaith** [comment]
pending

**Comment by ShusenTang** [comment]
> 另外缺失 3.5_output1.png 图像
> 
> ![3 5_output1](https://user-images.githubusercontent.com/16971804/70152504-4ee3d800-16e8-11ea-970d-c4662125617f.png)

图像缺失问题已解决 27267ea

**Comment by SwordFaith** [comment]
实际上是灰度图像，只是可视化时增强了对比度，通道这里的表述确实有事实性错误
