### ISSUE TITLE
第五章的小标题规范&图片缺失

### ISSUE THREAD

**Issue by ShusenTang** [TrickyGo/Dive-into-DL-TensorFlow2.0#20]
* 第五章图片缺失，注意用多少添加多少不要又一下全部加进来了
* 另外小标题规范一下，按照原书小标题来

**Comment by ShusenTang** [comment]
第四章小标题也存在同样的问题

另外每一节开头的标题标号加上:
![image](https://user-images.githubusercontent.com/16498688/70498917-e0bd6c00-1b52-11ea-9ad4-653c9cb00c13.png)

另外
![image](https://user-images.githubusercontent.com/16498688/70499078-51648880-1b53-11ea-85e4-e77ae083ff01.png)

反正大家每更新一节之后就去网页看看有没有问题（最后是更新前就在本地预览一下），上述问题在网页版一看就看出来了

**Comment by TrickyGo** [comment]
Roger!

**Comment by TrickyGo** [comment]
Problem solved. Thanks!
