### ISSUE TITLE
第四五章相对路径链接插入方式有误

### ISSUE THREAD

**Issue by ShusenTang** [TrickyGo/Dive-into-DL-TensorFlow2.0#21]
如下图链接是不对的
![image](https://user-images.githubusercontent.com/16498688/70500377-5ecf4200-1b56-11ea-8d85-6421c36d1e30.png)

建议直接像下面那样不插链接而是直接放文本，指定节号即可
<img width="550" alt="QQ20191210-135853@2x" src="https://user-images.githubusercontent.com/16498688/70500524-b8d00780-1b56-11ea-888a-19637993b86e.png">

**Comment by SwordFaith** [comment]
fixed
