### ISSUE TITLE
3.16.3 转换为nparray的时候使用的是pytorch的api

### ISSUE THREAD

**Issue by timor1988** [TrickyGo/Dive-into-DL-TensorFlow2.0#24]
n_train = train_data.shape[0]
train_features = torch.tensor(all_features[:n_train].values, dtype=torch.float)
test_features = torch.tensor(all_features[n_train:].values, dtype=torch.float)
train_labels = torch.tensor(train_data.SalePrice.values, dtype=torch.float).view(-1, 1)

**Comment by archersama** [comment]
已修复
