### ISSUE TITLE
2.2.5 运算的内存开销 tf.add中没有out参数

### ISSUE THREAD

**Issue by liuhe6** [TrickyGo/Dive-into-DL-TensorFlow2.0#26]
“如果想避免这个临时内存开销，我们可以使用运算符全名函数中的out参数。”
tf.add没有out参数，请确定：）

**Comment by SwordFaith** [comment]
是的，inplace 部分的文本部分没有随代码一起改动，稍晚些会修复解释文本的错误，多谢指正

**Comment by liuhe6** [comment]
不客气，你们加油：）
