### ISSUE TITLE
3.9.4代码缩进问题

### ISSUE THREAD

**Issue by kirk0306** [TrickyGo/Dive-into-DL-TensorFlow2.0#27]
IndentationError: expected an indented block

**Comment by SwordFaith** [comment]
是 code 里的 ipynb 么？麻烦贴下截图

**Comment by kirk0306** [comment]
![image](https://user-images.githubusercontent.com/16445247/71793867-18e89980-3082-11ea-938b-2ea86d7eb28e.png)
忘记截图了，在这里补充
另外这教程很不错，感谢！

**Comment by SwordFaith** [comment]
fix了
