### ISSUE TITLE
3.5 读取小批量 像素标准化

### ISSUE THREAD

**Issue by taichuai** [TrickyGo/Dive-into-DL-TensorFlow2.0#30]
3.5 读取小批量
并除以255使得所有像素的数值均在0到1之间
应该加一个 map函数作映射
def data_trans(x, y):
    x = tf.cast(x, tf.float32)
    x = x / 255
    return x, y

train_iter = tf.data.Dataset.from_tensor_slices((x_train, y_train)).map(data_trans).batch(256)

**Comment by archersama** [comment]
不理解为什么要加map函数做映射

**Comment by taichuai** [comment]
> 不理解为什么要加map函数做映射

因为像素点的值是 0-255

**Comment by archersama** [comment]
这个是读取数据，为了展示作用，原书就是这样做的

**Comment by taichuai** [comment]
也对哦，忘记了，不过做映射也是一样 问题不大 哈哈



---原始邮件---
发件人: "archersama"<notifications@github.com&gt;
发送时间: 2020年1月21日(周二) 晚上9:18
收件人: "TrickyGo/Dive-into-DL-TensorFlow2.0"<Dive-into-DL-TensorFlow2.0@noreply.github.com&gt;;
抄送: "zero_to_zero"<1126423412@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [TrickyGo/Dive-into-DL-TensorFlow2.0] 3.5 读取小批量 像素标准化 (#30)



这个是读取数据，为了展示作用，原书就是这样做的

**Comment by archersama** [comment]
不过除以255，图片展示效果应该不一样了

**Comment by taichuai** [comment]
这个是一个通道的，应该没什么区别吧



---原始邮件---
发件人: "archersama"<notifications@github.com&gt;
发送时间: 2020年1月21日(周二) 晚上9:32
收件人: "TrickyGo/Dive-into-DL-TensorFlow2.0"<Dive-into-DL-TensorFlow2.0@noreply.github.com&gt;;
抄送: "zero_to_zero"<1126423412@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [TrickyGo/Dive-into-DL-TensorFlow2.0] 3.5 读取小批量 像素标准化 (#30)



不过除以255，图片展示效果应该不一样了
