### ISSUE TITLE
3.2小节最后部分代码有点小问题(网页版文档)，多输入了一个t

### ISSUE THREAD

**Issue by Angrybirds1** [TrickyGo/Dive-into-DL-TensorFlow2.0#32]
![image](https://user-images.githubusercontent.com/24362834/73412224-e9f0db00-4342-11ea-89a6-bc0f613415b7.png)

**Comment by Angrybirds1** [comment]
print(ttrue_w, w)

**Comment by SwordFaith** [comment]
收到，现在修改
