### ISSUE TITLE
9.4 锚框  colab地址， 希望对你们有帮助

### ISSUE THREAD

**Issue by honeyshine75** [TrickyGo/Dive-into-DL-TensorFlow2.0#40]
我跟着pytorch那个版本改写成了tensorflow版本，当然，可能有错误或者使用不当的函数，希望相互指教，或者能对你们有帮助。

colab地址：https://colab.research.google.com/drive/1u5EUfErT-3G76vy7CMbXs7-tbJF4els5

**Comment by archersama** [comment]
非常感谢，建议您可以提出pr，我们做出审阅，如果没有问题，可以直接合并您的代码



---原始邮件---
发件人: "honeyshine75"<notifications@github.com&gt;
发送时间: 2020年3月17日(周二) 晚上6:09
收件人: "TrickyGo/Dive-into-DL-TensorFlow2.0"<Dive-into-DL-TensorFlow2.0@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [TrickyGo/Dive-into-DL-TensorFlow2.0] 9.4 锚框  参考 (#40)




 
我跟着pytorch那个版本改写成了tensorflow版本，当然，可能有错误或者使用不当的函数，希望相互指教，或者能对你们有帮助。
 
colab地址：https://colab.research.google.com/drive/1u5EUfErT-3G76vy7CMbXs7-tbJF4els5

**Comment by honeyshine75** [comment]
不了，还是麻烦你们有时间写一下吧，就算是抛砖引玉，因为我觉得我的代码有很多需要改进的，等你们出了代码我再学习你们对于tf的使用

**Comment by honeyshine75** [comment]
9.6 目标检测数据集（皮卡丘）

https://colab.research.google.com/drive/1vetYX9RtIwDxs7GEcwxpov0l1-ouVUu-

**Comment by archersama** [comment]
非常感谢

**Comment by honeyshine75** [comment]
9.8 区域卷积神经网络（R-CNN）系列
其实这个大部分是文字，有个roi_pooling的实现我没在tensorflow里面找到，就仿照着别人的写了个。
坐等你们更新后再看看你们怎么写的
https://colab.research.google.com/drive/1zqFCulsz5EmAv_fsC5hq07GswNsUITB1

**Comment by honeyshine75** [comment]
9.9 语义分割和数据集
https://colab.research.google.com/drive/1sQS1Uu8dZ2AbEUIZBRtbAkv2plu_z9hF

**Comment by archersama** [comment]
非常感谢，很有帮助，我们会尽快进行审阅和合并

**Comment by honeyshine75** [comment]
9.10. 全卷积网络（FCN） 
https://colab.research.google.com/drive/10QJ2yZWyTpGwcBp4L5CEPOWVqkc0Tybf

估计你们也会自己重新看一遍，我感觉我写的这个和原书的差距有些大(不过本来也就是简单的说明哥原理用的

**Comment by honeyshine75** [comment]
9.12. 实战Kaggle比赛：图像分类（CIFAR-10）
https://colab.research.google.com/drive/1oAvOZCTk7UB1rUWIrUYJaZKKS1u8AqyE

**Comment by honeyshine75** [comment]
9.11 样式迁移(我的参数效果可能还不是很好)
https://colab.research.google.com/drive/1C_hARTfpYtDJm6CVU2IKvVqqlRVi3vSy

**Comment by LIANGQINGYUAN** [comment]
已经审阅合并完毕，非常感谢！😄
另外补充了最后的9.13
https://colab.research.google.com/drive/146IoL0nVN7HOA3sUJ08zAGbngmwTArDp?usp=sharing

**Comment by honeyshine75** [comment]
> 已经审阅合并完毕，非常感谢！😄
> 另外补充了最后的9.13
> https://colab.research.google.com/drive/146IoL0nVN7HOA3sUJ08zAGbngmwTArDp?usp=sharing

赞
