### ISSUE TITLE
d2lzh_tensorflow2缺失

### ISSUE THREAD

**Issue by zhangasia** [TrickyGo/Dive-into-DL-TensorFlow2.0#63]
请问d2lzh_tensorflow2这个包在哪可以下载？

**Comment by Skyexu** [comment]
code 目录下就有哦， code/d2lzh_tensorflow2

**Comment by zhangasia** [comment]
> 
> 
> code 目录下就有哦， code/d2lzh_tensorflow2

谢谢哥们
