### ISSUE TITLE
6.4 和 6.5 小结中，损失函数缺少一个参数，导致训练结果不正确

### ISSUE THREAD

**Issue by sunshine-zkf** [TrickyGo/Dive-into-DL-TensorFlow2.0#64]
l = tf.reduce_mean(tf.losses.sparse_categorical_crossentropy(y,outputs))
该损失函数缺少参数 **from_logits = True**。在计算输出是没有使用激活函数softmax，因此需要在损失函数上指定，即令from_logits = True。故损失函数应该为：
l = tf.reduce_mean(tf.losses.sparse_categorical_crossentropy(y,outputs,**from_logits=True**))

错误结果：

epoch 50, perplexity 100.705286, time 1.76 sec
分开
 - 分开                                                  
不分开
 - 不分开                                                  
epoch 100, perplexity 27.005527, time 1.85 sec
分开
 - 分开                                                  
不分开
 - 不分开 我                                                
epoch 150, perplexity 1019.865201, time 1.80 sec
分开
 - 分开象元元乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘
不分开
 - 不分开元元乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘
epoch 200, perplexity 1020.654544, time 1.73 sec
分开
 - 分开象元元乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘
不分开
 - 不分开元元乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘
epoch 250, perplexity 1020.654544, time 1.75 sec
分开
 - 分开象元元乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘
不分开
 - 不分开元元乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘乘

**Comment by archersama** [comment]
了解,感谢指正

**Comment by pengfei-chen** [comment]
👍

**Comment by archersama** [comment]
已修正
