### ISSUE TITLE
网页版项目地址无法访问

### ISSUE THREAD

**Issue by HanwenQin** [TrickyGo/Dive-into-DL-TensorFlow2.0#72]
如题

**Comment by TrickyGo** [comment]
你好，这个地址可以访问https://trickygo.github.io/Dive-into-DL-TensorFlow2.0/#/，请问你指的是这个吗？目前由于mxnet和tensorflow的区别有些功能无法进行简洁的转换，所以有个别章节缺失，其余章节均可访问。
