### ISSUE TITLE
d2lzh_tensorflow2缺失，项目文件亦没有code目录

### ISSUE THREAD

**Issue by hurun** [TrickyGo/Dive-into-DL-TensorFlow2.0#76]
导入库缺失，项目代码也没有code，请问哪里可以获取，只发现utils.py含有相关代码

**Comment by archersama** [comment]
您好,该代码位于https://github.com/TrickyGo/Dive-into-DL-TensorFlow2.0/tree/master/code/d2lzh_tensorflow2 中，使用时需要下载下来放到和代码同一级目录中
