### ISSUE TITLE
编写规范建议

### ISSUE THREAD

**Issue by youngxhui** [TrickyGo/Dive-into-DL-TensorFlow2.0#8]
1. 需要将一些专有名词规范话，例如：

- tensorflow or Tensorflow
- tensor or Tensor

2. 单词与汉字之间，数字与汉字之间是否要保留空格，例如：

- Tensorflow是一个 or Tensorflow 是一个

3. 行内代码是否要专门括起来，原书是括起来的，例如：

- tensor or `tensor`

**Comment by archersama** [comment]
多谢，因为前期主要在赶工，所以没注意，以后会注意按照原书格式更改
